# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    - id: prettier
      files: ^frontend/
      types_or: [javascript, jsx, ts, tsx]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    - id: eslint
      files: ^frontend/
      types_or: [javascript, jsx, ts, tsx]
      additional_dependencies:
      - eslint
      - typescript
      - '@typescript-eslint/parser'
      - '@typescript-eslint/eslint-plugin'
