name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build-Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist/

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: backend/src/main/resources/static

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Maven Build
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v4
        with:
          name: theworkofart.jar
          path: backend/target/theworkofart.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: theworkofart.jar
          path: backend/target

      - name: Login Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: 'true'
          tags: "cmezzavilla/theworkofart:latest"
          context: .
          build-args: |
            GITHUB_SHA=${{github.sha}}

  deploy-on-render:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Render Deployment
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}
    environment:
      name: theworkofart
      url: https://theworkofart.onrender.com/
